services:
  dyslexics_frontend:
    build:
      context: .
      # tags:
      #   - ghcr.io/niflheimdevs/frontend
    image: ghcr.io/niflheimdevs/dyslexics-clock/frontend
    # container_name: frontend
    ports:
      - 3001:3001
networks:
  - dyslexic_backend_network
