package exception

type GeneralError string
type SpecificError string

const (
	EMAIL_TAKEN        SpecificError = "EMAIL_TAKEN"
	EMAIL_INVALID      SpecificError = "EMAIL_INVALID"
	EMAIL_NOT_VERIFIED SpecificError = "EMAIL_NOT_VERIFIED"

	USERNAME_TAKEN     SpecificError = "USERNAME_TAKEN"
	USERNAME_TOO_SHORT SpecificError = "USERNAME_TOO_SHORT"
	USERNAME_TOO_LONG  SpecificError = "USERNAME_TOO_LONG"

	PHONE_INVALID SpecificError = "PHONE_INVALID"
	PHONE_TAKEN   SpecificError = "PHONE_TAKEN"

	USERNAME_PASSWORD_WRONG SpecificError = "USERNAME_PASSWORD_WRONG"

	PASSWORD_INVALID    SpecificError = "PASSWORD_INVALID"
	PASSWORD_TOO_SHORT  SpecificError = "PASSWORD_TOO_SHORT"
	PASSWORD_TOO_LONG   SpecificError = "PASSWORD_TOO_LONG"
	PASSWORD_NO_DIGIT   SpecificError = "PASSWORD_NO_DIGIT"
	PASSWORD_NO_CAPITAL SpecificError = "PASSWORD_NO_CAPITAL"
	PASSWORD_NO_SMALL   SpecificError = "PASSWORD_NO_SMALL"

	OTP_INVALID                SpecificError = "OTP_INVALID"
	OTP_EXPIRED_OR_BAD_SESSION SpecificError = "OTP_EXPIRED_OR_BAD_SESSION"
	BAD_SESSION                SpecificError = "BAD_SESSION"

	DATABASE_ERROR      SpecificError = "DATABASE_ERROR"
	CACHE_ERROR         SpecificError = "CACHE_ERROR"
	MICROSERVICE_ERROR  SpecificError = "MICROSERVICE_ERROR"
	SERVICE_UNAVAILABLE SpecificError = "SERVICE_UNAVAILABLE"

	AUTH_INVALID_CREDENTIALS  SpecificError = "AUTH_INVALID_CREDENTIALS"
	AUTH_TOKEN_EXPIRED        SpecificError = "AUTH_TOKEN_EXPIRED"
	AUTH_ACCESS_DENIED        SpecificError = "AUTH_ACCESS_DENIED"
	AUTH_GENERATE_TOKEN_ERROR SpecificError = "AUTH_GENERATE_TOKEN_ERROR"

	MISSING_REQUIRED_FIELD SpecificError = "MISSING_REQUIRED_FIELD"

	MISSING_FILE SpecificError = "MISSING_FILE"
	CAST_ERROR   SpecificError = "CAST_ERROR"

	USER_NOT_FOUND SpecificError = "USER_NOT_FOUND"

	FORMAT_NOT_SUPPORTED SpecificError = "FORMAT_NOT_SUPPORTED"
	FILE_TOO_LARGE       SpecificError = "FILE_TOO_LARGE"

	PROJECT_NOT_FOUND SpecificError = "PROJECT_NOT_FOUND"

	CHAT_NOT_FOUND SpecificError = "CHAT_NOT_FOUND"

	USER_NOT_OWNER SpecificError = "USER_NOT_OWNER"

	ALREADY_HAS_BID      SpecificError = "ALREADY_HAS_BID"
	BID_NOT_FOUND        SpecificError = "BID_NOT_FOUND"
	INCREASE_NOT_ALLOWED SpecificError = "INCREASE_NOT_ALLOWED"

	NOT_PROPER_PROJECT_STATE SpecificError = "NOT_PROPER_PROJECT_STATE"

	INSUFFICIENT_BALANCE SpecificError = "INSUFFICIENT_BALANCE"

	ALREADY_A_MEMBER SpecificError = "ALREADY_A_MEMBER"
	NOT_A_MEMBER     SpecificError = "NOT_A_MEMBER"

	LACKS_PERMISSION SpecificError = "LACKS_PERMISSION"

	Token_EXPIRED SpecificError = "TOKEN_EXPIRED"
)

const (
	UNAUTHORIZED   GeneralError = "UNAUTHORIZED"
	CONFLICT_ERROR GeneralError = "CONFLICT_ERROR"
	INTERNAL_ERROR GeneralError = "INTERNAL_ERROR"
	NOT_FOUND      GeneralError = "NOT_FOUND"
	BAD_REQUEST    GeneralError = "BAD_REQUEST"
	LIMIT_EXCEED   GeneralError = "LIMIT_EXCEED"
	UNPROCESSABLE  GeneralError = "UNPROCESSABLE"
	FORBIDDEN      GeneralError = "FORBIDDEN"
)
