// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/NiflheimDevs/dyslexics-clock/bootstrap"
	"github.com/NiflheimDevs/dyslexics-clock/internal/application/service"
	"github.com/NiflheimDevs/dyslexics-clock/internal/application/service/implement"
	"github.com/NiflheimDevs/dyslexics-clock/internal/delivery/handler"
	"github.com/NiflheimDevs/dyslexics-clock/internal/delivery/middleware/authentication"
	"github.com/NiflheimDevs/dyslexics-clock/internal/delivery/middleware/panicwall"
	"github.com/NiflheimDevs/dyslexics-clock/internal/domain/message_broker"
	pkg2 "github.com/NiflheimDevs/dyslexics-clock/internal/domain/pkg"
	"github.com/NiflheimDevs/dyslexics-clock/internal/domain/repository"
	"github.com/NiflheimDevs/dyslexics-clock/internal/infra/database/driver"
	"github.com/NiflheimDevs/dyslexics-clock/internal/infra/database/postgres"
	driver2 "github.com/NiflheimDevs/dyslexics-clock/internal/infra/message_broker/driver"
	"github.com/NiflheimDevs/dyslexics-clock/internal/infra/message_broker/mosquitto"
	"github.com/NiflheimDevs/dyslexics-clock/internal/pkg"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(di *bootstrap.Di) (*App, error) {
	constants := ProvideConstants(di)
	pool := driver.ConnectSQL(di)
	alarmRepo := repositoryimpl.NewAlarmRepo(pool)
	client := driver2.ConnectMosquitto(di)
	alarmEventPublisher := mosquitto.NewAlarmEventPublisher(client)
	timePublisher := mosquitto.NewTimePublisher(client)
	requestPublisher := mosquitto.NewRequestPublisher(client)
	publisherService := serviceimpl.NewPublisherService(alarmEventPublisher, timePublisher, requestPublisher)
	alarmService := serviceimpl.NewAlarmService(alarmRepo, publisherService)
	validatorWrapper := pkg.NewValidatorWrapper()
	alarmHandler := handler.NewAlarmHandler(constants, alarmService, validatorWrapper)
	deviceRepo := repositoryimpl.NewDeviceRepo(pool)
	secretSauce := pkg.NewSecretSauce()
	jwt := serviceimpl.NewJWT(constants)
	deviceService := serviceimpl.NewDeviceService(deviceRepo, secretSauce, jwt, publisherService)
	deviceHandler := handler.NewDeviceHandler(constants, deviceService, validatorWrapper, publisherService)
	handlers := &Handlers{
		AlarmHandler:  alarmHandler,
		DeviceHandler: deviceHandler,
	}
	panicWall := panicwall.NewPanicWall()
	authentication := midauth.NewAuth(deviceRepo, constants, jwt)
	middlewares := &Middlewares{
		PanicWall: panicWall,
		Auth:      authentication,
	}
	deviceEventService := serviceimpl.NewDeviceEventService(alarmRepo, requestPublisher, deviceRepo)
	deviceEventSubscriber := mosquitto.NewDeviceEventSubscriber(client, deviceEventService)
	app := &App{
		Handlers:              handlers,
		Middlewares:           middlewares,
		DeviceEventSubscriber: deviceEventSubscriber,
	}
	return app, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(driver.ConnectSQL)

var RepositoryProviderSet = wire.NewSet(repositoryimpl.NewDeviceRepo, repositoryimpl.NewAlarmRepo, wire.Bind(new(repository.AlarmRepo), new(*repositoryimpl.AlarmRepo)), wire.Bind(new(repository.DeviceRepo), new(*repositoryimpl.DeviceRepo)))

var PkgProviderSet = wire.NewSet(pkg.NewValidatorWrapper, pkg.NewSecretSauce, wire.Bind(new(pkg2.SecretSauce), new(*pkg.SecretSauce)), wire.Bind(new(pkg2.Validator), new(*pkg.ValidatorWrapper)))

var ServiceProviderSet = wire.NewSet(serviceimpl.NewDeviceService, serviceimpl.NewAlarmService, serviceimpl.NewJWT, serviceimpl.NewDeviceEventService, serviceimpl.NewPublisherService, wire.Bind(new(service.DeviceService), new(*serviceimpl.DeviceService)), wire.Bind(new(service.AlarmService), new(*serviceimpl.AlarmService)), wire.Bind(new(service.JWT), new(*serviceimpl.JWT)), wire.Bind(new(service.DeviceEventService), new(*serviceimpl.DeviceEventService)), wire.Bind(new(service.PublisherService), new(*serviceimpl.PublisherService)))

var MessageBrokerProviderSet = wire.NewSet(driver2.ConnectMosquitto, mosquitto.NewRequestPublisher, mosquitto.NewDeviceEventSubscriber, mosquitto.NewAlarmEventPublisher, mosquitto.NewTimePublisher, wire.Bind(new(messagebroker.RequestPublisher), new(*mosquitto.RequestPublisher)), wire.Bind(new(messagebroker.DeviceEventSubscriber), new(*mosquitto.DeviceEventSubscriber)), wire.Bind(new(messagebroker.AlarmEventPublisher), new(*mosquitto.AlarmEventPublisher)), wire.Bind(new(messagebroker.TimePublisher), new(*mosquitto.TimePublisher)))

var HandlerProviderSet = wire.NewSet(handler.NewAlarmHandler, handler.NewDeviceHandler, wire.Struct(new(Handlers), "*"))

var MiddlewareProviderSet = wire.NewSet(panicwall.NewPanicWall, midauth.NewAuth, wire.Struct(new(Middlewares), "*"))

var ProviderSet = wire.NewSet(
	PkgProviderSet,
	ProvideConstants,
	ProvideEnv,
	DatabaseProviderSet,
	RepositoryProviderSet,
	ServiceProviderSet,
	MessageBrokerProviderSet,
	HandlerProviderSet,
	MiddlewareProviderSet,
)

func ProvideConstants(container *bootstrap.Di) *bootstrap.Constants {
	return container.Const
}

func ProvideEnv(container *bootstrap.Di) *bootstrap.Env {
	return container.Env
}

type Handlers struct {
	AlarmHandler  *handler.AlarmHandler
	DeviceHandler *handler.DeviceHandler
}

type Middlewares struct {
	PanicWall *panicwall.PanicWall
	Auth      *midauth.Authentication
}

type App struct {
	Handlers              *Handlers
	Middlewares           *Middlewares
	DeviceEventSubscriber messagebroker.DeviceEventSubscriber
}
