// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/NiflheimDevs/dyslexics-clock/bootstrap"
	"github.com/NiflheimDevs/dyslexics-clock/internal/application/service"
	"github.com/NiflheimDevs/dyslexics-clock/internal/application/service/implement"
	"github.com/NiflheimDevs/dyslexics-clock/internal/delivery/handler"
	"github.com/NiflheimDevs/dyslexics-clock/internal/delivery/middleware/authentication"
	"github.com/NiflheimDevs/dyslexics-clock/internal/delivery/middleware/panicwall"
	pkg2 "github.com/NiflheimDevs/dyslexics-clock/internal/domain/pkg"
	"github.com/NiflheimDevs/dyslexics-clock/internal/domain/repository/postgres"
	"github.com/NiflheimDevs/dyslexics-clock/internal/infra/database/driver"
	"github.com/NiflheimDevs/dyslexics-clock/internal/infra/database/postgres"
	"github.com/NiflheimDevs/dyslexics-clock/internal/pkg"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(di *bootstrap.Di) (*App, error) {
	constants := ProvideConstants(di)
	pool := driver.ConnectSQL(di)
	alarmRepo := repositoryimpl.NewAlarmRepo(pool)
	alarmService := serviceimpl.NewAlarmService(alarmRepo)
	validatorWrapper := pkg.NewValidatorWrapper()
	alarmHandler := handler.NewAlarmHandler(constants, alarmService, validatorWrapper)
	deviceRepo := repositoryimpl.NewDeviceRepo(pool)
	secretSauce := pkg.NewSecretSauce()
	jwt := serviceimpl.NewJWT(constants)
	deviceService := serviceimpl.NewDeviceService(deviceRepo, secretSauce, jwt)
	deviceHandler := handler.NewDeviceHandler(constants, deviceService, validatorWrapper)
	handlers := &Handlers{
		AlarmHandler:  alarmHandler,
		DeviceHandler: deviceHandler,
	}
	panicWall := panicwall.NewPanicWall()
	authentication := midauth.NewAuth(deviceRepo, constants, jwt)
	middlewares := &Middlewares{
		PanicWall: panicWall,
		Auth:      authentication,
	}
	app := &App{
		Handlers:    handlers,
		Middlewares: middlewares,
	}
	return app, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(driver.ConnectSQL)

var RepositoryProviderSet = wire.NewSet(repositoryimpl.NewDeviceRepo, repositoryimpl.NewAlarmRepo, wire.Bind(new(repository.AlarmRepo), new(*repositoryimpl.AlarmRepo)), wire.Bind(new(repository.DeviceRepo), new(*repositoryimpl.DeviceRepo)))

var PkgProviderSet = wire.NewSet(pkg.NewValidatorWrapper, pkg.NewSecretSauce, wire.Bind(new(pkg2.SecretSauce), new(*pkg.SecretSauce)), wire.Bind(new(pkg2.Validator), new(*pkg.ValidatorWrapper)))

var ServiceProviderSet = wire.NewSet(serviceimpl.NewDeviceService, serviceimpl.NewAlarmService, serviceimpl.NewJWT, wire.Bind(new(service.DeviceService), new(*serviceimpl.DeviceService)), wire.Bind(new(service.AlarmService), new(*serviceimpl.AlarmService)), wire.Bind(new(service.JWT), new(*serviceimpl.JWT)))

var HandlerProviderSet = wire.NewSet(handler.NewAlarmHandler, handler.NewDeviceHandler, wire.Struct(new(Handlers), "*"))

var MiddlewareProviderSet = wire.NewSet(panicwall.NewPanicWall, midauth.NewAuth, wire.Struct(new(Middlewares), "*"))

var ProviderSet = wire.NewSet(
	PkgProviderSet,
	ProvideConstants,
	ProvideEnv,
	DatabaseProviderSet,
	RepositoryProviderSet,
	ServiceProviderSet,
	HandlerProviderSet,
	MiddlewareProviderSet,
)

func ProvideConstants(container *bootstrap.Di) *bootstrap.Constants {
	return container.Const
}

func ProvideEnv(container *bootstrap.Di) *bootstrap.Env {
	return container.Env
}

type Handlers struct {
	AlarmHandler  *handler.AlarmHandler
	DeviceHandler *handler.DeviceHandler
}

type Middlewares struct {
	PanicWall *panicwall.PanicWall
	Auth      *midauth.Authentication
}

type App struct {
	Handlers    *Handlers
	Middlewares *Middlewares
}
